language: go
go:
- 1.7
- master
install:
- go get -d -v ./...
script:
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: bin/twitterfarm
  on:
    repo: andefined/twitterfarm
