sudo: false
language: go
go:
    - 1.7
    - tip
install:
    - go get -t -v ./...
script:
    - "./build.sh"
deploy:
    provider: releases
    skip_cleanup: true
    api_key:
        secure: $GITHUB_TOKEN
    file: bin/twitterfarm
    on:
        tags: true
