sudo: false
language: go
go:
    - 1.7
    - 1.8
env:
  global:
    - VERSION=$(cat VERSION)
before_script:
  - go get -t -v ./...
script:
    - go vet ./...
before_deploy:
    - mkdir -p release
    - "GOOS=linux  GOARCH=amd64 go build -o release/twitterfarm-v$VERSION-linux-amd64"
    - "GOOS=darwin GOARCH=amd64 go build -o release/twitterfarm-v$VERSION-darwin-amd64"
    - "GOOS=windows GOARCH=amd64 go build -o release/twitterfarm-v$VERSION-windows-amd64"
deploy:
    overwrite: true
    provider: releases
    skip_cleanup: true
    api_key:
        secure: $GITHUB_TOKEN
    file:
        - "release/twitterfarm-v$VERSION-linux-amd64"
        - "release/twitterfarm-v$VERSION-darwin-amd64"
        - "release/twitterfarm-v$VERSION-windows-amd64"
    on:
        tags: true
