sudo: false
language: go
go:
    - 1.7
    - tip
before_script:
    - go get -t -v ./...
script:
    - go vet -v ./...
deploy:
    overwrite: true
    provider: releases
    skip_cleanup: true
    api_key:
        secure: $GITHUB_TOKEN
    file: bin/twitterfarm
    on:
        tags: true
